shell = "/usr/bin/zsh"

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor.vi_mode_style]
shape = "Beam"
blinking = "On"

[colors.primary]
background = "#282828"
foreground = "#d4be98"

[colors.normal]
black = "#3c3836"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

[colors.bright]
black = "#3c3836"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"


[mouse]
bindings = [
  { mouse = "Right", mods = "Control", action = "Paste" },
]

[selection] 
save_to_clipboard = true

[window]
padding = { x = 10, y = 5 }
decorations = "Full"
opacity = 0.97
dynamic_title = true
decorations_theme_variant = "Dark"

[font]
normal = { family = "Source Code Pro", style = "Regular" }
bold = { family = "Source Code Pro", style = "Bold" }
italic = { family = "Source Code Pro", style = "Italic" }
bold_italic = { family = "Source Code Pro", style = "Bold Italic" }
size = 15
